name: uplayer
description: Stream and Listen Youtube music
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  youtube_explode_dart: ^1.12.4
  just_audio: ^0.9.34
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  just_audio_background: ^0.0.1-beta.10
  audio_video_progress_bar: ^1.0.1
  rxdart: ^0.27.7
  lottie: ^2.3.2
  marquee: ^2.2.3
  permission_handler: ^10.2.0
  path_provider: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6
  percent_indicator: ^4.2.3
  background_downloader: ^7.8.1
  blobs: ^2.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/fonts/
     - assets/fonts/sfPro/
     - assets/images/
     - assets/icons/
     - assets/lottie/
     -
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sfPro/SF-Pro-Display-Regular.ttf
        - asset: assets/fonts/sfPro/SF-Pro-Display-Semibold.ttf
          weight: 600
        - asset: assets/fonts/sfPro/SF-Pro-Display-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 900

